### ISSUE TITLE
Compose v2

### ISSUE THREAD

**Issue by TheEndIsNear** [prakhar1989/docker-curriculum#16]
I have been following along with your tutorial, but with docker-compose version 1.7.0 there is no longer the option for --x-networking. 

Looking at the docker documentation, there is now a v2 for the compose file. Would suggest updating the tutorial to reflect the newer version of compose.

**Comment by coreyzev** [comment]
here is my example compose file based on v2. It needs much less to make it work.

```
version: '2'

services:
  es:
    image: elasticsearch
  web:
    image: coreyzev/foodtrucks
    command: python app.py
    ports:
      - "5000:5000"
    volumes:
      - .:/code
```

This worked without modification.
